// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNHpmvh2Kyr9Iv_mSaC7gmlGdS1-Tpuz0',
    appId: '1:767312118825:web:6b54f56e02cb0b7639c838',
    messagingSenderId: '767312118825',
    projectId: 'myapp-e61dd',
    authDomain: 'myapp-e61dd.firebaseapp.com',
    storageBucket: 'myapp-e61dd.firebasestorage.app',
    measurementId: 'G-C2W8GTG79S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-AOscjuSpynt8ODAYawdw9pW2dhMSr78',
    appId: '1:767312118825:android:5e58de16973c329539c838',
    messagingSenderId: '767312118825',
    projectId: 'myapp-e61dd',
    storageBucket: 'myapp-e61dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO2QgSCnyls8LsW-Z8ST8w8km8ukBxlsw',
    appId: '1:767312118825:ios:cbdf65fc289ebde539c838',
    messagingSenderId: '767312118825',
    projectId: 'myapp-e61dd',
    storageBucket: 'myapp-e61dd.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAO2QgSCnyls8LsW-Z8ST8w8km8ukBxlsw',
    appId: '1:767312118825:ios:cbdf65fc289ebde539c838',
    messagingSenderId: '767312118825',
    projectId: 'myapp-e61dd',
    storageBucket: 'myapp-e61dd.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNHpmvh2Kyr9Iv_mSaC7gmlGdS1-Tpuz0',
    appId: '1:767312118825:web:cf9f1262af7f398639c838',
    messagingSenderId: '767312118825',
    projectId: 'myapp-e61dd',
    authDomain: 'myapp-e61dd.firebaseapp.com',
    storageBucket: 'myapp-e61dd.firebasestorage.app',
    measurementId: 'G-3T1VHTZVY5',
  );

}